User.create(email: "dileep@gmail.com", password: "123456", password_confirmation: "123456")

exam = Exam.create(name: "Exam 1")
  subject = Subject.create(name: "Subject 1", exam: exam)
    topic = Topic.create(name: "Topic 1", subject: subject)
      chapter = Chapter.create(name: "Chapter 1", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
      chapter = Chapter.create(name: "Chapter 2", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
    topic = Topic.create(name: "Topic 2", subject: subject)
      chapter = Chapter.create(name: "Chapter 1", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
      chapter = Chapter.create(name: "Chapter 2", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
  subject = Subject.create(name: "Subject 2", exam: exam)
    topic = Topic.create(name: "Topic 1", subject: subject)
      chapter = Chapter.create(name: "Chapter 1", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
      chapter = Chapter.create(name: "Chapter 2", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
    topic = Topic.create(name: "Topic 2", subject: subject)
      chapter = Chapter.create(name: "Chapter 1", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
      chapter = Chapter.create(name: "Chapter 2", topic: topic)
        question = Question.create(name: "Question 1", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 2", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)
        question = Question.create(name: "Question 3", chapter: chapter)
          Option.create(name: "Option 1", question: question)
          Option.create(name: "Option 2", question: question)
          Option.create(name: "Option 3", question: question)